version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - circle-cache
      - run:
          name: Install dependencies
          command: cd client && npm install
      - run:
          name: Build client
          command: cd client && npx webpack
      - run:
          name: Resolve/Update Dependencies
          command: cd server && stack --no-terminal setup
      - run:
          name: Run tests
          command: cd server && stack --no-terminal test
      - run:
          name: Install executable
          command: cd server && stack --no-terminal install
      - save_cache:
          name: Cache Dependencies
          key: circle-cache
          paths:
            - "~/.stack"
            - "server/.stack-work"
            - "client/node_modules"
      - store_artifacts:
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: ~/.local/bin/dayta-exe
          destination: dayta-exe
      - store_artifacts:
          path: client/dist/
          destination: client
